### ISSUE TITLE
Sending messages with headers

### ISSUE THREAD

**Issue by jasonmccallister** [basis-company/nats.php#20]
Is there current a way to send messages with headers to a JetStream stream? I peaked around in the code but could not find it.

Thank you!

**Comment by adam-lmi** [comment]
Use Payload for that, like this:

```php
use Basis\Nats\Message\Payload;

$stream->publish(
	'mailer.greet',
	new Payload(
		"Example message",
		['HeaderName'=>'Value']
	)
);
```
