### ISSUE TITLE
Connecting to NGS?

### ISSUE THREAD

**Issue by jasonmccallister** [basis-company/nats.php#21]
I'm trying to use this library to connect to NGS with TLS, a JWT, and a NKEY... I'm getting the following errors when connecting using the following configuration:

```php
$config = new Configuration([
    'host' => 'tls://connect.ngs.global:4222'
    'nkey' => 'mynkey',
    'jwt' => 'myjwt',
]);
```

The specific error message is coming from `Client->connect()` on line 91, `Connection error`. https://github.com/basis-company/nats.php/blob/main/src/Client.php#L91

**Comment by nekufa** [comment]
Seems you use invalid configuration.
Host is just a hostname, not connection string with protocol prefix and port postfix.

Try connect using:
```php
$config = new Configuration([
    'host' => 'connect.ngs.global',
    'port' => 4222,
    'nkey' => 'mynkey',
    'jwt' => 'myjwt',
]);
```

**Comment by jasonmccallister** [comment]
That did the trick, I used the Go client connection and that included the tls and port in the host. Thank you!
