### ISSUE TITLE
[ question ] Acking messages?

### ISSUE THREAD

**Issue by 6562680** [basis-company/nats.php#27]
On event based system we have two primary flows of work - events and commands.

Events usually works like a radio (online) or youtube (online + store) - who want to get, he get. Otherwise ignore - nothing changes.
Commands usually works like a queue (message) - at least one slave should do command he received from the master and if command failed - retry few times until retry timeout expires.

Commands NEED to "ack" message if done or if failed. But should "deny" if exception happened. How to "ack" message in your library? I guess it ack always or something? (JetStream for example has only method ->handle() that wants messageHandler/emptyHandler), but the payload is instance of Payload::class, that doesnt have method ->ack()...

And also AckPolicy::Explicit is set up by default. But... guess it ack message automatically (inside basis-company/nats library code) cus of autoask on NATS side requires other mode enabled.

**Comment by siamakmontazer** [comment]
I have the same problem

**Comment by nekufa** [comment]
oh, sorry, i've miss the issue :(
right now if there were no exceptions message is acked in the background. when you get the message from stream it contains replyTo header and this is subject for acking message. if there were no feedback - message would be back in the stream.

**Comment by nekufa** [comment]
@6562680 @siamakmontazer do you have any problems with current approach? we can implement some alternate methods if you can share your ideal api usage :)

**Comment by kirill-voronov** [comment]
@nekufa Hello, could you please clarify how to use replyTo header for ACKing (and NACKing also)?
For example, if I need to implement message delay like described here https://github.com/nats-io/nats-server/issues/2846#issuecomment-1030721734 ?

**Comment by ro0NL** [comment]
an example on how to ack/nack explicitly would be nice

**Comment by ro0NL** [comment]
AFAIK here https://github.com/basis-company/nats.php/blob/e368664335e9955fd058d3ae64a617bc10bfa9f1/src/Client.php#L332-L337 the message is acked, effectively making AckPolicy::EXPLICIT a no-op for end-users :(
