### ISSUE TITLE
[ feature ] Ephemeral consumer

### ISSUE THREAD

**Issue by oxidmod** [basis-company/nats.php#32]
Current implementation does not support [ephemeral consumers](https://docs.nats.io/using-nats/developer/develop_jetstream/consumers#ephemeral-consumers) for JetSream. They can be useful for irregular task when you need get some data from stream for metrics calculation and don't want to persist consumers in NATS. Ofcourse you can create durable consumers and then remove them in the end of the task but ephemeral consumers look like more suitable concept.

I create a [PR](https://github.com/basis-company/nats.php/pull/34) with simple implementation but have some issue with checks.
Hope somebody will help me with checks and I'm open for change requests to this feature.

**Comment by nekufa** [comment]
thanks! merged and released as 0.10.0
