### ISSUE TITLE
[ question ] How do I wait for pubsub messages?

### ISSUE THREAD

**Issue by fideloper** [basis-company/nats.php#35]
Hi!

What's the best way to keep a processing listening/wait for pubsub messages to come in?

It looks like the following is The Way™ to go about this - do I need to put `$client->process()` in a loop and set its timeout?

```php
        $client = new \Basis\Nats\Client;
        $client->subscribe('some-topic', function ($message) {
            printf("Data: %s\r\n", $message->getBody());
        });

        $client->process();
```

Thanks!

**Comment by nekufa** [comment]
hi @fideloper!
process has an optional argument for timeout.
that value is in seconds, hope this can be used in your case?

```php
$client->subscribe('topic', function ($msg) {});
$client->process(30 * 60); // process messages for 30 minutes
```
