### ISSUE TITLE
Issue with automatic bucket creation during put

### ISSUE THREAD

**Issue by jasonmccallister** [basis-company/nats.php#37]
When using this library and trying to put an item into a KV, if the KV does not exist, this library will automatically create a KV store.

Example:

```php
$client->getApi()->getBucket('my-bucket')->put($key, $value);
```

This will create a bucket that appears to be incompatible with other libraries (e.g. the Go SDK for NATS). The only solution is to remove the KV store and allow the Go SDK to create it. 

1. Should an exception be thrown if there is no bucket? 
2. Also, the library is uppercasing the store names during creation, is that expected?

**Comment by nekufa** [comment]
Hello, i'm not sure that this approach should be kept. In my opinion we need to keep maximum compatibility with standard. Would you like to make merge request with fix or will wait until i have time to fix up this? Thanks for feedback!

**Comment by jasonmccallister** [comment]
I'm not sure when, but I will take an attempt at trying to make a PR.

However, I think there are some design choices. In the Go SDK, if you try to access a non-existent bucket, it returns an error. Should this library throw an exception when the bucket does not exist?
