### ISSUE TITLE
Nkeys auth failed

### ISSUE THREAD

**Issue by dobro-lubov** [basis-company/nats.php#38]
Took the keys from the examples
server: 
```
authorization: {
  users: [
    { nkey: UDXU4RCSJNZOIQHZNWXHXORDPRTGNJAHAHFRGZNEEJCPQTT2M7NLCNF4 }
  ]
}
```
client:
```
$c = new NatsClient(new Configuration([
          'host' => 'nats',
          'nkey' => 'SUACSSL3UAHUDXKFSNVUZRF5UHPMWZ6BFDTJ7M6USDXIEDNPPQYYYCU3VY'
    ]));
$c->ping(); //Authorization Violation
```

I tried to generate keys, the problem persists

**Comment by nekufa** [comment]
Hello!
I have no idea how to reproduce it, we have some functional tests that cover nkey auth methods.
Would you like to make reproducable test or maybe fix this yourself?

**Comment by nekufa** [comment]
@akademic great, reproduce is the first step to fix.
feel free to fix that and make merge request!
