### ISSUE TITLE
Publish Failures

### ISSUE THREAD

**Issue by mgraf-dozuki** [basis-company/nats.php#44]
First off, thanks for working on a php client for nats.  Its very helpful and appreciated.

While using your library I have noticed that when I am trying to use publish() if there is an issue connecting to the nats server, I am not seeing exceptions thrown to indicate that something has gone amiss.  Looking at the code in Client it seems like processSocketException() gets called in a loop without some kind of break, and all exceptions get swallowed up and continued.  The best I have found so far is to call ping() before I do a publish() to see if that works.

Do you have any better suggestions?  The built-in retry is helpful, but at some point (say after a few seconds), I want to know that it has failed and be able to log it.

**Comment by nekufa** [comment]
Hello @mgraf-dozuki sorry for the deferred response.
This is hidden reconnect implementation - client will reconnect and send request again.
You can simply disable this option via configration.reconnect property.
Let me know if i miss anything :)
