### ISSUE TITLE
[Question]Supported JetStream API subset

### ISSUE THREAD

**Issue by g41797** [basis-company/nats.php#59]
In our project we will have php producers/consumers and go consumers.
Also we need broker with event sourcing support.

as far as I understand NATS JetStream (JS) supports this pattern.

on go side we will use [nats.go](https://github.com/nats-io/nats.go) with relative new [js client](https://github.com/nats-io/nats.go/tree/main/jetstream)
and I am sure that all js functionality is supported by go lib

I understand that nats.php uses [JetStream wire API](https://docs.nats.io/reference/reference-protocols/nats_api_reference), but still is not clear actually supported API

Do you have stories/cases/links of nats.php usage in the production?

**Comment by nekufa** [comment]
Hi, @g41797!

You are right - all jetstream api is based on standard subjects using publish subscribe - nats itself has listeners on special subjects to implement jetstream solution. This means you can take any client with minimal pub/sub implementation and talk to special subjects to use that api. We implement all that was needed includes bucket support with history - you can see example in readme.

We have a lot of microservices that sends request to each other using async approach with nats. All logic are implemented using jobs (same as jsonrpc method). We have subject naming convention to define which streams are used by which service, and optionally microservice can have more that one stream on per-job basis.

If this can helps, source is available at basis-company/framework.php repository. There are some points you can check:
- nats.consume is configuration consumer to listen on job requests
- nats.subject is used to define subject name for a job
- send method if dispatcher is used to put call request. 
- any service is started using module.starter
  - async registration to web service (it downloads all assets) 
  - async subscription to event service. 

It's not documented, but this is not a rocket science :)
Let me know if this helps or you have any other questions

**Comment by g41797** [comment]
it isn't rocket science, but it was quickest **_rocket speed_** response ever i got in github
thanks a lot
some questions:
 - how do you manage jobs? e.g. cancel running, process of progress indication etc 
 - do you have go processes in this flow?

**Comment by g41797** [comment]
if your are ready to use open source code in your projects, i will be happy to help on golang side 
e.g. php job submitter - go workers,
Cloud Events on both sides of the wire, ...
if you have some ideas for cooperation - let me know (btw i hate db, javascript and gui)

meanwhile i will continue to learn php - very impressive language
with one big disadvantage (_for me_) - lack of multi-threading

**Comment by nekufa** [comment]
thanks for proposal, i'll keep in mind it till it would be actual!

for me, there are many disadvantages of php, like legacy named functions, a lot of special characters - static methods, instance method call, namespace separator, annotations.. i like that it's moving to more typed syntax, but we still can't define type - array of classes.

multit-hreading is not a big issue - in real life we start applications in kubernetes and it's better to have design solution that can distribute tasks over multiple pods and nodes, instead of have multi threads in a single container/vm.

we use a lot of open source code and contributes anything that can help other ones! you can check current framework dependencies - a lot of symfony components and other libraries.

**Comment by g41797** [comment]
agree - running one task(job) per worker process is right design decision because it simplifies job management (e.g. failure of the job).
it's common misconception that MT == multiple workers within one process.
for me mt is just convenient way of development
