### ISSUE TITLE
Header in Msg

### ISSUE THREAD

**Issue by alifpay** [basis-company/nats.php#7]
Hi, thank you for repo, you do very good thing..

https://github.com/basis-company/nats.php/blob/main/src/Message/Msg.php

I can not find Header in Msg class. How to send headers ?

**Comment by nekufa** [comment]
Hi,

Headers are the part of message payload.
You can see an example here:
https://github.com/basis-company/nats.php/blob/main/tests/StreamTest.php#L27-L29

**Comment by timur265** [comment]
Hi nekufa. I have a related question, I try to add api-key inside header. Haw can use the example which you've sent above with publish logic?

**Comment by nekufa** [comment]
@timur265
Stream is a simple wrapper over subject api.
https://github.com/basis-company/nats.php/blob/main/src/Stream/Stream.php#L90

So you can simply use 
```php
$client->publish('subject', new Payload($json, ['api-key' => $key]));
```

**Comment by timur265** [comment]
Hi @nekufam thanks for your respond. But should data inside $json variable be string type? Something like that
"{a: b}" ?

**Comment by nekufa** [comment]
@timur265 yep, you need to serialize data, constructor takes string argument (not mixed like parse api).
There are not a lot of source code and i hope it is easy to read
https://github.com/basis-company/nats.php/blob/main/src/Message/Payload.php#L27

**Comment by timur265** [comment]
@nekufa got it. thanks!
