### ISSUE TITLE
Info message unavailable

### ISSUE THREAD

**Issue by ro0NL** [basis-company/nats.php#80]
There's an edge case error when the connection is dropped:

```
Cannot assign null to property Basis\Nats\Connection::$infoMessage of type Basis\Nats\Message\Info

/app/vendor/basis-company/nats/src/Connection.php:202
/app/vendor/basis-company/nats/src/Connection.php:127
/app/vendor/basis-company/nats/src/Client.php:207
/app/vendor/basis-company/nats/src/Client.php:127
/app/vendor/basis-company/nats/src/Consumer/Consumer.php:105
```

But the API expects non-nullable, and im wondering if it should be refactored a bit :)

**Comment by nekufa** [comment]
interesting case, looks like we need to check that info message was received or throw an exception :)
btw, have no idea how to cover that with tests)

**Comment by ro0NL** [comment]
It's an edge case. Let's move on.
