### ISSUE TITLE
Basis\Nats\Message\Msg, no getPayload method?

### ISSUE THREAD

**Issue by devbastic** [basis-company/nats.php#83]
Hi,

I'm trying the basic publish/subscribe example and get: 

Fatal error: Uncaught Error: Call to undefined method Basis\Nats\Message\Msg::getPayload()

And indeed; Basis\Nats\Message\Msg doesn't seem to have a getPayload method?

**Comment by nekufa** [comment]
hi @devbastic
thanks, that is mistake in readme, you can access payload property directly, it has public visibility.
would you like to update readme file via merge request?

**Comment by devbastic** [comment]
PR done, cheers. Working fine now.
