### ISSUE TITLE
What happens if Msg is used in published or Payload

### ISSUE THREAD

**Issue by SuheylZ** [basis-company/nats.php#93]
For streams we have a publish message whose signature is like 
`publish(string $subject, mixed $payload)`

so usually we send anything as payload, if I make a NATS message and publish it like 

```
  $msg = new Msg();
  $msg->subject = $subject;
  $msg->payload = new Payload($headers, $data);

  $stream->publish($subject, $msg);
  
  // Or could we do something like
  $client->publish($msg);
```

is this the correct appproach?

**Comment by nekufa** [comment]
No, message does not contain the destination (subject).\
You can checkout readme file for real world examples.
