### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by ro0NL** [basis-company/nats.php#97]
would be nice to have 1.x stable

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable. (https://semver.org/)

**Comment by nekufa** [comment]
i would like to merge microservices feature #96\
wait some weeks till it would be stable and then push major release\
what do you think, is it okay?

**Comment by ro0NL** [comment]
@nekufa i think before releasing 1.0 it's wise to add psalm and/or psalm CI analysis ;)

**Comment by nekufa** [comment]
hi @ro0NL, i've just released 1.0, it's stable now
