### ISSUE TITLE
Service stats processing time

### ISSUE THREAD

**Issue by izytechAB** [basis-company/nats.php#99]
ServiceEndpoint getProcessingTime returns float. nats requires an int when unmarshal.

./nats micro stats core

nats: error: json: cannot unmarshal number 0.03245377540588379 into Go struct field EndpointStats.endpoints.processing_time of type time.Duration

solution
    public function getProcessingTime(): **int**
    {
        return $this->processing_time * 1e9;
    }

**Comment by izytechAB** [comment]
missed that it also need a round on the return, itherwise we get deprecated warings in php8+

        return round($this->processing_time * 1e9);

**Comment by nekufa** [comment]
hi @izytechAB thanks! would you like to make merge request?\
you can create it using github web interface, no local repo clone is needed

**Comment by izytechAB** [comment]
I have created a PR. Not so descriptive text on the request.

**Comment by nekufa** [comment]
thanks, merged, released in 0.26.1
